name: Setup module
description: Setup new agency module
title: "Setup"
labels:
  - MT
body:
  - type: dropdown
    id: target_store_channel
    attributes:
      label: Target store channel
      description: Select the store channel to target for this setup.
      options:
        - Production
        - Beta (Private)
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: setup_checklist
    attributes:
      label: Setup checklist
      options:
        - label: Created initial `Setup` PR with agency module configuration [ℹ️](https://github.com/mtransitapps/mtransit-for-android/wiki/HowToAddNewTransitAgencyModule#agency-config-setup)
        - label: "[Generated screenshots](../actions/workflows/mt-record-screenshots.yml) _during service hours_"
        - label: "[Generated images](../actions/workflows/mt-image-gen.yml)"
        - label: Created initial Store listing [ℹ️](https://github.com/mtransitapps/mtransit-for-android/wiki/HowToAddNewTransitAgencyModule#play-store-setup)
        - label: Updated [mtransitapps.github.io/dev/build-status](https://github.com/mtransitapps/mtransitapps.github.io/blob/master/dev/build-status/index.html)
        - label: Updated [ISSUE_TEMPLATE/modules-list.md](https://github.com/mtransitapps/mtransit-for-android/blob/master/.github/ISSUE_TEMPLATE/modules-list.md)
        - label: "[Published to store `Internal` channel](https://play.google.com/console/)"
        - label: "[Published to store `${{ inputs.target_store_channel }}` channel](https://play.google.com/console/)"
        - label: "[Enabled store `${{ inputs.target_store_channel }}` channel](../actions/workflows/mt-store-channels.yml) for the repo."
        - label: If published to store `Production` channel, updated recommended [modules](https://github.com/mtransitapps/mtransit-for-android/blob/master/app-android/src/main/res/raw/modules.json) & [version](https://github.com/mtransitapps/mtransit-for-android/blob/master/app-android/src/main/res/values/modules_values.xml)
        - label: Updated [wiki/Apps](https://github.com/mtransitapps/mtransit-for-android/wiki/Apps) or [wiki/BETA](https://github.com/mtransitapps/mtransit-for-android/wiki/BETA)

  - type: markdown
    attributes:
      value: "[More info](https://github.com/mtransitapps/mtransit-for-android/wiki/HowToAddNewTransitAgencyModule)"
